### ISSUE TITLE
Scrolling issue in Shortucts app

### ISSUE THREAD

**Issue by andreaguida** [chrenn/swish-dl#10]
Hi, I love Swish but I've a huge problem with Shortcuts app on my Mac mini M1 (macOS 13.2.1): when Swish is active, even if I set to "ignore Shortcuts", the scrolling doesn't work in the shortcuts editor. If I close Swish, the scrolling work. I've also tried to deactivate the listener with no luck. Can you fix this? 

https://user-images.githubusercontent.com/54178949/219903332-ebe966a5-a5bf-4a88-96b6-4d92d12b26fc.mp4

**Comment by chrenn** [comment]
Unfortunately I can't, see #5.

It's an issue with Swift UI and Apple's Accessibility API which blocks the whole system under certain conditions. I submitted the bug to Apple with a reproducible code sample, but have not heard back yet: https://github.com/feedback-assistant/reports/issues/368. I'll try to arrange a technical call with Apple in the coming weeks, let's see how it goes.

In the meantime, you can user bigger strokes while scrolling. The timeout occurs at the start of the scroll. After that, scrolling will be smooth again.

**Comment by andreaguida** [comment]
I get this, thanks!
