### ISSUE TITLE
Mouse offset after moving window around

### ISSUE THREAD

**Issue by fardage** [chrenn/swish-dl#11]
Hello there
When I resize a window using swish and then move the window, there is always an offset between the mouse and the window. I think the mouse used to stay at the relative position to the window. Is this a known issue?

MacOS 13.4
Swish version 10.1

https://github.com/chrenn/swish-dl/assets/48010396/c0b4315d-e0c8-4810-951f-178b9b725f24

**Comment by chrenn** [comment]
Hi, this is a workaround to prevent the window size form being cut off when unsnapping from the bottom and right desktop boundaries. You can try this with Rectangle by snapping to the bottom right corner then dragging the window back: it does not snap back to its original size.
