### ISSUE TITLE
Triple-Tap/MiddleClick

### ISSUE THREAD

**Issue by JeremiaWilliams** [chrenn/swish-dl#12]
On a mouse, you can middle click to close tabs and also to open a link in a new background tab.

Swish already implements a way to close tabs. Would you consider adding a feature so that a triple tap works like a middle click to open a link in a new tab?

**Comment by chrenn** [comment]
I'm afraid that's out of scope for Swish. I personally use [Middle](http://middleclick.app/) to map a force tap to middle click.

**Comment by chrenn** [comment]
That's also out of scope, sorry.
