### ISSUE TITLE
Extend to bottom & top Shortcut

### ISSUE THREAD

**Issue by avviyah** [chrenn/swish-dl#14]
Would you consider adding a shortcut which resizes a window to extend to the bottom of the screen and the top of the screen? Sometimes I have a chat window, Finder window, or Terminal window open and would like it to vertically take up the whole screen, but maintain its horizontal width.

**Comment by chrenn** [comment]
That's out of scope as it is already built into macOS, see: [https://www.reddit.com/r/apple/comments/5atjdg/macos_double_click_on_the_edge_of_a_window_when/](https://www.reddit.com/r/apple/comments/5atjdg/macos_double_click_on_the_edge_of_a_window_when/).

Also, this repo is not really intended for feature requests.
