### ISSUE TITLE
Tab Close/Pop Out problem

### ISSUE THREAD

**Issue by avviyah** [chrenn/swish-dl#15]
When using a three-finger tap gesture to middle click to close a tab via a different app, Swish sometimes does the "Detach Tab" action.

How to replicate: Tap 3 fingers down on tab. Release one finger slightly before the other two. "Detach Tab" gesture eats the middle-click action.

**Comment by chrenn** [comment]
There's only so much user intent you can extract from touch events via CGEventTaps, so just disable the "Detach Tab" gesture if it bothers you.

Again, this is not a support forum.
