### ISSUE TITLE
Active event listener + fn Modifier breaks keyboard input on Fn+Arrow keys and Pos1/End

### ISSUE THREAD

**Issue by thekerub** [chrenn/swish-dl#2]
Pressing either the Fn+Arrow keys or Pos1/End on external keyboards freezes all keyboard input on all keyboards, including the MacBooks own keyboard. This only happens with the following settings (which is the default setting iirc):

- "Active Event Listener" enabled
- "Arrow Hotkeys" enabled and set to arrows
- "Super Modifier" set to "fn" ONLY (key combinations including the fn key do not trigger this bug)

After pressing either button (or button combo) all keyboard inputs from any keyboard are not recognized anymore. This lasts a few seconds but seems to stack with multiple presses.

If only Active Event Listener is active and Arrow Keys is not active, no freezing occurs.

If only Arrow Hotkeys is active and Active Event Listener is not active, no freezing occurs. However, gestures are never executed (e.g. fn+up will make the little maximize icon show but the window is not maxed).

Tested this on a Logitech MX Keys (the version for both Windows and Mac) and a mechanical USB keyboard. I do not own an Apple keyboard so couldn't try that.
This does NOT happen when pressing fn+arrows on the MacBooks own keyboard, only on external keyboards.

MacBook Pro 14", latest MacOS 12.3 (21E230), latest Swish 1.8.1.

This one was driving me crazy, I thought my keyboard or my Mac was defective. Turned off Arrow Hotkeys for now but I thought it was interesting because iirc Hotkeys + Event listener is the default setting.

**Comment by chrenn** [comment]
Thanks for the bug report. Key handling is pretty tricky and inconsistent with Apple's APIs. Also not very well documented.

I've tested Swish on a generic external keyboard as well as Apple's Magic Keyboard , where it seemed to work fine, but not that specific Logitech one. I'll do some tests as soon as I get my hands on an external keyboard again.

For now you'll probably have to deactivate the active event listener or arrow hotkeys. Sorry about that!

**Comment by chrenn** [comment]
This should hopefully be fixed in the latest 1.9 Beta. Can you check this?

**Comment by thekerub** [comment]
Sorry for the late answer, issue is fixed in 1.9.1 stable release.
