### ISSUE TITLE
System Preferences window opens and disappears when "Automatically Reactivate Pinch & Swipe" is enabled

### ISSUE THREAD

**Issue by said50** [chrenn/swish-dl#3]
When "Automatically Reactivate Pinch & Swipe" is enabled, the System Preferences window opens up, goes to Trackpad and disappears again. I know this is to re-enable macOS trackpad settings, but it can be quite annoying because it interrupts what I'm doing (it's especially annoying when I'm for typing for example).  Is there a fix for this? Or workaround or something?

**Comment by chrenn** [comment]
Swish runs an Apple Script to launch System Preferences and re-enable some settings. However, System Preferences should be launching hidden. Not sure why it would be behaving differently on your machine. I can post the script if you like to check for yourself. You could also just turn that option off, not sure if it's even doing much. CGEventTaps are kind of a black hole.
