### ISSUE TITLE
Most Window and Snapping gestures may not work in Mission Control & App Expose when [Super Modifier Key] is enabled

### ISSUE THREAD

**Issue by YonglinChann** [chrenn/swish-dl#4]
Most Window and Snapping gestures may not work in Mission Control & App Expose when [Super Modifier Key] is enabled.
For normal use, I must work with super modifier at the same time.

My Version:  1.8.1
OS Version: macOS Monterey 12.5.1 (21G83)
Type of Equipment: MacBook Air 2020 (M1)

Looking forward to your reply！

**Comment by chrenn** [comment]
Not sure if I understand that correctly. Can you be more specific?

**Comment by YonglinChann** [comment]
> 
Thank you very much for your reply！

There is a 'super modifier key' setting in the settings. When I set the 'Super Modifier Key' , all gestures will only take effect once in Mission Control & App Expose, and then when I need to use the gestures again, both require a super modifier key to be attached to Mission Control & App Expose to take effect.

**Comment by YonglinChann** [comment]
> Mission Control & App Expose

I thought this was a normal phenomenon due to the [ Super Modifier Key] setting, but then i thought it was a Bug. Because every time I reboot the program after I exit it completely, I can successfully use the gesture function again in the Mission Control & App Expose interface, but only once, the follow-up failed again.

**Comment by chrenn** [comment]
Hi, is this issue still persisting on your side? I have not been able to recreate it on my machine.
